apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-release-finals-chart-myapp
  labels:
    app: my-release-myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-release-myapp
  template:
    metadata:
      labels:
        app: my-release-myapp
    spec:
      containers:
      - name: myapp
        image: {{ .Values.myapp.image.repository }}
        ports:
        - containerPort: {{ .Values.myapp.port }}
        env:
        - name: MONGODB_URI
          value: {{ .Values.myapp.environment.MONGODB_URI }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
