apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: {{ include "finals-chart.name" . }}-myapp
spec:
  type: NodePort 
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
    nodePort: 30002
  selector:
    app: {{ include "finals-chart.name" . }}-myapp

