services:
  mongo:
    image: mongo:latest
    hostname: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myUserAdmin
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
      - ./mongodb_folder:/docker-entrypoint-initdb.d
    networks:
      - mynetwork
    

  myapp:
    image: noabl/flask-app:temp
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://myUserAdmin:changeme@mongo:27017/?authSource=admin
    depends_on:
      - mongo
    networks:
      - mynetwork

  test_main:
    build:
      context: .
      dockerfile: dockerfile.test
    environment:
      - MONGODB_URI=mongodb://myUserAdmin:changeme@mongo:27017/?authSource=admin
    depends_on:
      - mongo
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge