FROM python:alpine
WORKDIR /usr/src/app
COPY ./requirements.txt ./
RUN pip install --upgrade pip
RUN pip install flask
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# (if needed, typically not necessary for testing)
EXPOSE 8082
CMD ["pytest", "test_main.py"]
