apiVersion: v1
kind: Pod
metadata:
  name: jenkins-runner
spec:
  containers:
  - name: builder
    image: ezezeasy/ez-docker-helm-build:1.41
    imagePullPolicy: Always
    securityContext:
      privileged: true
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"

  - name: python-test
    image: python:3.9-slim
    command: ["sleep"]
    args: ["infinity"]
    imagePullPolicy: Always
    securityContext:
      privileged: false

  - name: docker-compose
    image: docker/compose:latest
    command: ["sleep"]
    args: ["infinity"]
    imagePullPolicy: Always
    securityContext:
      privileged: true
    volumeMounts:
      - name: docker-socket
      ##not sure about path:
        mountPath: /var/run/docker.sock

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket