
# myapp values
myapp:
  image: 
    repository: noabl/flask-app:latest
  environment:
    MONGODB_URI: mongodb://myUserAdmin:changeme@mongo:27017/?authSource=admin
  port: 5000

# service values
service:
  port: 5000

# ingress values
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: myuniqueapp.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# autoscaling values
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  #mongo-chart/values.yaml

# MongoDB values
mongo:
  enabled: true
  replicaCount: 1
  image: mongo:latest
  hostname: mongo
  environment:
    MONGO_INITDB_ROOT_USERNAME: myUserAdmin
    MONGO_INITDB_ROOT_PASSWORD: changeme
  service:
    type: ClusterIP
    port: 27017
  resources: {}

