apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave  # Ensure you have a name for the Pod
  labels:
    jenkins: slave
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "250m"
          memory: "256Mi"
    - name: builder
      image: maven:3.6.3-jdk-8
      command:
        - cat
      tty: true
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "500m"
          memory: "512Mi"
