apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finals-chart.fullname" . }}-myapp
  labels:
    app: {{ include "finals-chart.name" . }}-myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "finals-chart.name" . }}-myapp
  template:
    metadata:
      labels:
        app: {{ include "finals-chart.name" . }}-myapp
    spec:
      containers:
      - name: myapp
        image: {{ .Values.myapp.image.repository }}
        ports:
        - containerPort: {{ .Values.myapp.port }}
        env:
        - name: MONGODB_URI
          value: {{ .Values.myapp.environment.MONGODB_URI }}
      volumes:
      - name: mongo-data
        emptyDir: {}
      - name: mongo-initdb
        configMap:
          name: mongo-initdb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finals-chart.fullname" . }}-mongo
  labels:
    app: {{ include "finals-chart.name" . }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "finals-chart.name" . }}-mongo
  template:
    metadata:
      labels:
        app: {{ include "finals-chart.name" . }}-mongo
    spec:
      containers:
      - name: mongo
        image: {{ .Values.mongo.image }}
        args: ["--dbpath", "/data/db"]
        command: ["mongod", "--bind_ip_all"]
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongo.environment.MONGO_INITDB_ROOT_USERNAME }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongo.environment.MONGO_INITDB_ROOT_PASSWORD }}
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: mongo-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mongo-data
        emptyDir: {}
      - name: mongo-initdb
        configMap:
          name: mongo-initdb