{{/*This file defines the Ingress resource for routing HTTP/HTTPS traffic to your services.*/}}
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: {{ include "finals-chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "finals-chart.fullname" . }}-myapp
                port:
                  number: {{ .Values.service.port }}

