apiVersion: v1
kind: Service
metadata:
  name: {{ include "finals-chart.fullname" . }}-myapp
  labels:
    app: {{ include "finals-chart.name" . }}-myapp
spec:
  type: NodePort 
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
    protocol: TCP
    name: http
    nodePort: 30001
  selector:
    app: {{ include "finals-chart.name" . }}-myapp
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "finals-chart.fullname" . }}-mongo
  labels:
    app: {{include "finals-chart.name" . }}-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: {{ include "finals-chart.name" . }}-mongo