apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: {{ include "finals-chart.name" . }}-myapp
spec:
  type: NodePort 
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
    nodePort: 30002
  selector:
    app: {{ include "finals-chart.name" . }}-myapp
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: {{ include "finals-chart.name" . }}-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo
  selector:
    app: {{ include "finals-chart.name" . }}-mongo

