#finals-chart/values.yaml

# MongoDB values
mongo:
  image: mongo:latest
  hostname: mongo
  environment:
    MONGO_INITDB_ROOT_USERNAME: myUserAdmin
    MONGO_INITDB_ROOT_PASSWORD: changeme

# ingress values
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# autoscaling values
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
