apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "finals-chart.fullname" . }}-ingress-app
spec:
  ingressClassName: nginx
  rules:
  - host:  myapp.local
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "finals-chart.fullname" . }}-myapp
            port:
              number: {{ .Values.service.port }}
  tls: []
