
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: {{ include "finals-chart.name" . }}-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo
  selector:
    app: {{ include "finals-chart.name" . }}-mongo
