apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb
data:
#Each key is a filename, and each value is the contents of the file.
#after a | , everything is a value key.
  initdb.js: |
    // Initialization script for MongoDB
    db.createUser({
      user: 'myUserAdmin',
      pwd: 'changeme',
      roles: [{ role: 'root', db: 'admin' }]
    });