apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb
data:
  initdb.js: |
    // Initialization script for MongoDB
    db.createUser({
      user: 'myUserAdmin',
      pwd: 'changeme',
      roles: [{ role: 'root', db: 'admin' }]
    });

  users.js: |
    const database = 'Project';
    const collectionName = 'Users';

    // Create a new database.
    use(database);

    // Create a new collection.
    db.createCollection(collectionName);

    const collection = db.getCollection(collectionName);

    const users = [
      {username: 'Noa', password: '1123'},
      {username: 'Mai', password: '2123'}
    ];

    collection.insertMany(users);
    collection.find();

  posts.js: |
    const database = 'Project';
    const collectionName = 'Posts';

    // Create a new database.
    use(database);

    // Create a new collection.
    db.createCollection(collectionName);

    const collection = db.getCollection(collectionName);

    const posts = [
      {username: 'Noa', _title: 'one', content: 'this info noa', likes: []},
      {username: 'Mai', _title: 'one', content: 'this info mai', likes: []},
      {username: 'Noa', _title: 'two', content: 'this info noa2', likes: []}
    ];

    collection.insertMany(posts);
    collection.find();
